all:	1 2 8 5 6 7 3 4
1:
	../diff 1.old 1.new > 1.diff
	../patch 1.old 1.diff > 1.result
	diff 1.new 1.result
2:
	../diff 2.old 2.new > 2.diff
	../patch 2.old 2.diff > 2.result
	diff 2.new 2.result
3:
	../diff 3.old 3.new > 3.diff
	../patch 3.old 3.diff > 3.result
	diff 3.new 3.result
4:
	../diff 4.old 4.new > 4.diff
	../patch 4.old 4.diff > 4.result
	diff 4.new 4.result
5:
	../diff 5.old 5.new > 5.diff
	../patch 5.old 5.diff > 5.result
	diff 5.new 5.result
6:
	../diff 6.old 6.new > 6.diff
	../patch 6.old 6.diff > 6.result
	diff 6.new 6.result
7:
	../diff 7.old 7.new > 7.diff
	../patch 7.old 7.diff > 7.result
	diff 7.new 7.result
8:
	../diff 8.old 8.new > 8.diff
	../patch 8.old 8.diff > 8.result
	diff 8.new 8.result
